name: Android Not-Prod nitro.build

on:
  push: # TODO: Remove this type after testing
    branches-ignore:
      - 'release/'
      - 'hotifix/'
  # Run on every pull request (except for release/* and hotfix/* branches)
  pull_request:
    branches-ignore:
      - 'release/'
      - 'hotifix/'
  # Manually trigger the workflow (https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#running-a-workflow)
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Cancel previous runs of this workflow

jobs:
  build-android:
    name: Android Build
    runs-on: ubuntu-latest
    env:
      NITRO_API_KEY: ${{ secrets.NITRO_API_KEY }}
      RELEASE_VERSION: 1.0.0+${{ github.head_ref || github.ref_name }}
      # ^^^ `version-name` will be used but to avoid gradle exception we need to set this env var
    steps:
      - uses: actions/checkout@v3

        # https://github.com/nitro-build/github-action-nitro-android#inputs
      - uses: nitro-build/github-action-nitro-android@v1
        id: nitro
        with:
          version-name: 1.0.0+${{ github.head_ref || github.ref_name }} # (see: docs/versioning.md)
          version-code: 1
          disable-version-name-from-package-json: yes
          disable-version-code-auto-generation: yes


      # (optional) Use GitHub Actions artifacts to store the apk
      - name: Store artifacts on GitHub
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.nitro.outputs.nitro-app-path }}

      # (optional) Upload the apk to Firebase App Distribution
      - name: Distribute apk to Firebase App Distribution
        run: |
          source ./scripts/env.sh
          APP_ID=$FIREBASE_PROD_ANDROID_APP_ID ./scripts/distribute-to-firebase.sh
        env:
          # required
          APK_OR_IPA_PATH: ${{ steps.nitro.outputs.nitro-app-path }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          # optional
          RELEASE_NOTES: Made by - ${{ github.actor }} - ${{ github.event.head_commit.message }}
