name: iOS https://nitro.build
on: [push]
jobs:
  build:
    runs-on: macos-12
    env:
      NITRO_API_KEY: ${{ secrets.NITRO_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: nitro-build/github-action-nitro-ios@v1
        id: nitro
      - uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.nitro.outputs.nitro-output-dir }}
