name: Android Not-Prod nitro.build

on:
  push: # TODO: Remove this type after testing
    branches-ignore:
      - 'release/'
      - 'hotifix/'
  # Run on every pull request (except for release/* and hotfix/* branches)
  pull_request:
    branches-ignore:
      - 'release/'
      - 'hotifix/'
  # Manually trigger the workflow (https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#running-a-workflow)
  workflow_dispatch:
    inputs:
      appEnvironment:
        description: 'Environment (TODO)'
        required: true
        default: 'Staging'
        type: choice
        options:
          - Production
          - Staging
          - QA

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Cancel previous runs of this workflow

jobs:
  build-android:
    name: Android Build
    runs-on: ubuntu-latest
    env:
      NITRO_API_KEY: ${{ secrets.NITRO_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: nitro-build/github-action-nitro-android@v1
        id: nitro
        with:
          # flavor: Staging|Production # optional (TODO: not implemented yet)
          version_name: 1.0.0+${{ github.head_ref || github.ref_name }} # (see: docs/versioning.md)
          version_code: 1 # (see: docs/versioning.md)
          disable_version_name_from_package_json: yes
          disable_version_code_auto_generation: yes
          verbose: yes
          debug: yes
          entry_file: index.TODO.js

      # (optional) Use GitHub Actions artifacts to store the apk
      - name: Store artifacts on GitHub
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.nitro.outputs.nitro-output-dir }}

      # (optional) Upload the apk to Firebase App Distribution
      - name: Distribute apk to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          APK_PATH: ${{ steps.nitro.outputs.nitro-output-dir }}/app-release.apk
          RELEASE_NOTES: Made by - ${{ github.actor }} # optional
        run: |
          source ./scripts/env.sh
          APP_ID=$FIREBASE_PROD_ANDROID_APP_ID ./scripts/distribute-to-firebase.sh
